dir .
dir ../../gcc/gcc
dir ../../gcc/gcc/ada
dir ../../gcc/gcc/cp
dir ../../gcc/gcc/fortran
dir ../../gcc/gcc/go
dir ../../gcc/gcc/java
dir ../../gcc/gcc/lto
dir ../../gcc/gcc/objc
dir ../../gcc/gcc/objcp
source ../../gcc/gcc/gdbinit.in
